### ISSUE TITLE
Give NixOS a try

### ISSUE THREAD

**Issue by miooochi** [stevewm/homelab#278]
## Greeting

Hi Steve, recently I've commited myself switching to NixOS on my daily-drivers and a few servers. I like it so much. I'd like to share my insights about NixOS with you and excit you to have a try :)

My configuration: https://github.com/yqlbu/nixos-config

## Background

NixOS, a Linux distribution built on top of the Nix package manager, can be described as "OS as Code." It employs declarative Nix configuration files to describe the entire state of the operating system.

Nix is a declarative package manager that enables users to declare the desired system state in configuration files (declarative configuration), and it takes responsibility for achieving that state.

The [NixOS & Flakes Book](https://nixos-and-flakes.thiscute.world/introduction/) is an amazing source to start the journey with. Let me know if you'd like to give it a try.

**Comment by stevewm** [comment]
Hey Kev! It's been a while, hope the mobile CI team is still going strong. Miss working with you guys.

I'm trying nix out in this repo at the moment to manage the dev environment (through devshell) and so far really liking it. NixOS is definitely on my radar to try out this year, it looks really cool. Will give your config a peruse as well for inspiration 😃

**Comment by yqlbu** [comment]
Cool, glad to know that you like it!
